### ISSUE TITLE
Node12 is being deprecated

### ISSUE THREAD

**Issue by Amndeep7** [sophos/factory-run-pipeline#40]
Workflow run that had warnings: https://github.com/mitre/heimdall2/actions/runs/4801546295

Specific warning about node 12 being deprecated:
```
 docker
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: sophos/factory-run-pipeline@master. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
```

Relevant line (I think): https://github.com/sophos/factory-run-pipeline/blob/master/action.yml#L23

**Comment by sophos-victoria** [comment]
Done. Thank you Amndeep!

**Comment by Amndeep7** [comment]
@sophos-victoria yall should probably also update your test workflow while we're at it: 

Workflow run: https://github.com/sophos/factory-run-pipeline/actions/runs/4833708142

Warnings: 
```
ci
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2, actions/setup-node@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
ci: src/withError.ts#L10
Unexpected any. Specify a different type
e2e
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: sophos/factory-run-pipeline@master. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
```

The checkout and setup-node actions are the ones that need to be updated to v3 (just changing the tag should be sufficient based off of the updating we had to do).  The third one is just yalls workflow which is based off of the master branch and not the change you'd made in the PR where that workflow was run so it was fixed on merge.

Regardless, thanks for the quick response!
