### ISSUE TITLE
New release including upgrade to node20

### ISSUE THREAD

**Issue by Amndeep7** [sophos/factory-run-pipeline#47]
You've updated the action to use the latest node version: https://github.com/sophos/factory-run-pipeline/commit/4074fe5e9bd2f3fa481e28073d5ecae230b6ca3e

However, there is no new release.  Can you please release the action again?

**Comment by marcfieser** [comment]
I have created a release for v2.2.0. You should be good to go. Thanks for the heads up.

**Comment by Amndeep7** [comment]
Thanks @marcfieser

**Comment by Amndeep7** [comment]
@marcfieser could you update the major version tag (v2) to point to the latest minor version as well?
