### ISSUE TITLE
Update major version only tag to point at latest release

### ISSUE THREAD

**Issue by Amndeep7** [sophos/factory-run-pipeline#48]
Thank you for pushing out v2.2.0.  Could you please make v2 point at that tag as well?  Currently it is still pointing at v2.1.0.

**Comment by marcfieser** [comment]
v2 updated to latest as well

**Comment by Amndeep7** [comment]
@marcfieser it seems that v2.2.0 and v2 are still pointing at different commits.  

v2.2.0 points at [19f9c40](https://github.com/sophos/factory-run-pipeline/commit/19f9c4044613b208b69ecd21a303f55c4299c1e7)

v2 points at [5949fe7](https://github.com/sophos/factory-run-pipeline/commit/5949fe78ca4cb9fe497400aeaa08de6d5ec86141)
